# This Dockerfile is meant to be run in a CI/CD pipeline to build the Flux project.

# -------
# BACKEND
# -------
FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim AS backend

WORKDIR /code

COPY . .
RUN dotnet publish Flux.Native -c Release -r win-x64 -o /build/native
RUN dotnet publish Flux.Web -c Release -o /build/web
RUN dotnet publish Flux.Web -c Release -r win-x64 -o /build/web-win-x64
RUN dotnet publish Flux.Web.Updater -c Release -r win-x64 -o /updater/web/win-x64
RUN dotnet publish Flux.Web.Updater -c Release -r win-x86 -o /updater/web/win-x86
RUN dotnet publish Flux.Web.Updater -c Release -r win-arm64 -o /updater/web/win-arm64
RUN dotnet publish Flux.Web.Updater -c Release -r linux-x64 -o /updater/web/linux-x64
RUN dotnet publish Flux.Web.Updater -c Release -r linux-arm64 -o /updater/web/linux-arm64
RUN dotnet publish Flux.Native.Updater -c Release -r win-x64 -o /updater/native/win-x64
RUN dotnet publish Flux.Native.Updater -c Release -r win-x86 -o /updater/native/win-x86
RUN dotnet publish Flux.Native.Updater -c Release -r win-arm64 -o /updater/native/win-arm64

# No osx because it needs codesign and it costs money...

# Copy the win-x64 executable to the root of the web folder
RUN cp /build/web-win-x64/Flux.Web.exe /build/web/Flux.Web.exe

WORKDIR /build/web

# Remove all .xml files
# (we cannot use <GenerateDocumentationFile>false</GenerateDocumentationFile>
# because we need it for swagger)
RUN find . -name "*.xml" -type f -delete

# Manually copy over the dbip-country-lite.mmdb file from /code to /build
# since for some reason it doesn't get copied over by the dotnet publish command
RUN cp /code/Flux.Web/dbip-country-lite.mmdb /build

# --------
# FRONTEND
# --------
FROM node:20.9.0 AS frontend

WORKDIR /code

COPY flux-web-client/package.json .
COPY flux-web-client/package-lock.json .
RUN npm install

COPY flux-web-client .
RUN npm run build
RUN mkdir /build && mv dist/* /build

# ---------
# AGGREGATE
# ---------
FROM mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim

RUN apt-get update -yq && apt-get install -y --no-install-recommends curl

WORKDIR /app/web

COPY --from=backend /build/web .
COPY --from=frontend /build ./wwwroot
COPY Flux.Web/dbip-country-lite.mmdb .

# Create a text file with all the files and folders in the current directory, not recursive, to be used by the updater
RUN ls -1 > build-files.txt

WORKDIR /app/native

COPY --from=backend /build/native /app/native

# Create a text file with all the files and folders in the current directory, not recursive, to be used by the updater
RUN ls -1 > build-files.txt

COPY --from=backend /updater /app/updater
