blank_issues_enabled: false
contact_links:
    - name: 📃 Documentation Issue
      url: https://github.com/flux/flux-docs/issues/new
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: 🤔 Questions and Help
      url: https://discourse.flux.dev/
      about: This issue tracker is not for support questions. Please refer to the Flux community's help and discussion forums.
