<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>Ruri</Authors>
    <Description>This is a library that can perform multiple tasks (yes, a lot, even infinitely many) that act on some input and return a certain output.</Description>
    <Copyright>Ruri 2022</Copyright>
    <PackageProjectUrl>https://github.com/openbullet/OpenBullet2/tree/master/RuriLib.Parallelization</PackageProjectUrl>
    <RepositoryUrl>https://github.com/openbullet/OpenBullet2/tree/master/RuriLib.Parallelization</RepositoryUrl>
    <PackageTags>parallelization; task; tasks; manager; taskmanager; multithreading; parallel; multithread; async;</PackageTags>
    <Version>1.0.6</Version>
    
    <!-- Performance optimizations -->
    <Optimize>true</Optimize>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IncludeSymbols>false</IncludeSymbols>
    <IncludeSource>false</IncludeSource>
    <TrimUnusedDependencies>true</TrimUnusedDependencies>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <AnalysisLevel>none</AnalysisLevel>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

</Project>
